Reland "Reland "Android: Suppress non-fatal exception in logcats when use_jacoco_coverage=true""
This reverts commit 52cc1d41c83a7fb91d3c51f4ed3f9f48b7506bf6.

Reason for reland: Not the cause

Original change's description:
> Revert "Reland "Android: Suppress non-fatal exception in logcats when use_jacoco_coverage=true""
>
> This reverts commit bf8b56106026abd79728e2614022f00184866305.
>
> Reason for revert: Speculative revert for https://crbug.com/1406790
>
> Original change's description:
> > Reland "Android: Suppress non-fatal exception in logcats when use_jacoco_coverage=true"
> >
> > This reverts commit f55cc9369bdc2b0677b32c39e70852ebd9eaf0d1.
> >
> > Reason for reland: No longer affects robolectric
> >
> > Original change's description:
> > > Revert "Android: Suppress non-fatal exception in logcats when use_jacoco_coverage=true"
> > >
> > > This reverts commit 1e0efe2a67cd48156a617e61559e2dd675813d95.
> > >
> > > Reason for revert: Breaks java code coverage, no .exec file is created.
> > >
> > > Original change's description:
> > > > Android: Suppress non-fatal exception in logcats when use_jacoco_coverage=true
> > > >
> > > > Stacks that appear in logcats draw attention and often get blamed as the
> > > > cause for failing tests.
> > > >
> > > > This one looks like:
> > > >
> > > > java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
> > > >   at ...
> > > >
> > > > Bug: 1334374
> > > > Change-Id: Ia7dd1eccf5edd923380bd3405d914174d2254239
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3935167
> > > > Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> > > > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > > > Reviewed-by: Benjamin Joyce (Ben) <bjoyce@chromium.org>
> > > > Commit-Queue: Benjamin Joyce (Ben) <bjoyce@chromium.org>
> > > > Cr-Commit-Position: refs/heads/main@{#1084407}
> > >
> > > Bug: 1334374
> > > Change-Id: I4090901b49987e1eb680668564a15986c06368ac
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4144419
> > > Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> > > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > > Cr-Commit-Position: refs/heads/main@{#1090353}
> >
> > Bug: 1334374
> > Change-Id: I3992c15ea17c7fd08a3e47527af0e370b1a81833
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4146140
> > Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> > Reviewed-by: Benjamin Joyce (Ben) <bjoyce@chromium.org>
> > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1091501}
>
> Bug: 1334374
> Change-Id: Iae68ed61de249e95d269ebc4cf8c76e633109fd0
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4161951
> Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
> Owners-Override: Arthur Sonzogni <arthursonzogni@chromium.org>
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/main@{#1091755}

Bug: 1334374
Change-Id: I3612438020abf291e1f11ffde08a76a07e490b11
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4162651
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1092257}
NOKEYCHECK=True
GitOrigin-RevId: 41ee46f110c5dc7079d22b532e6e2a81194582b1