[Android] Fix compilation with order_profiling=1
I'm guesing we haven't built this since rolling the NDK. I see errors of
the form:

In file included from ../../third_party/webrtc/modules/audio_coding/codecs/isac/fix/source/entropy_coding_neon.c:19:0:
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h: In function 'vshr_n_s32':
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h:3426:3: error: argument must be a constant
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h: In function 'vshl_n_s32':
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h:3798:3: error: argument must be a constant
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h: In function 'vshll_n_s16':
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h:4032:3: error: argument must be a constant
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h: In function 'vset_lane_s32':
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h:5082:3: error: argument must be a constant
third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/include/arm_neon.h:5082: confused by earlier errors, bailing out

One additional fix to md5sum is included.
NOTRY=true

Review URL: https://chromiumcodereview.appspot.com/18034029

git-svn-id: http://src.chromium.org/svn/trunk/src/build@211835 4ff67af0-8c30-449e-8e8b-ad334ec8d88c