Revert 251003 "Revert 250830 "Exclude notification strings for b..."
> Revert 250830 "Exclude notification strings for builds that dont..."
> 
> > Exclude notification strings for builds that dont use it.
> > 
> > BUG=326023
> > 
> > Review URL: https://codereview.chromium.org/160113002
> 
> Broke win64 sync tests, e.g. output:
> 
> c:\b\build\slave\cr-win-rel-x64\build\src\chrome\browser\sync\test\integration\sync_test.cc(707): error: Value of: UTF16ToASCII(browser()->tab_strip_model()->GetActiveWebContents()-> GetTitle())
>   Actual: ""
> Expected: "Notifications enabled"
> 
> TBR=aurimas@chromium.org
> 
> Review URL: https://codereview.chromium.org/163713002

Reverting the revert, since this wasn't responsible for the failures.

TBR=asvitkine@chromium.org

Review URL: https://codereview.chromium.org/164573002

git-svn-id: http://src.chromium.org/svn/trunk/src/build@251106 4ff67af0-8c30-449e-8e8b-ad334ec8d88c