Revert "Enable unused resource removal for android webview"
This reverts commit 0deb4b3b72afa40b35c55dc56d64fae28d7f160a.

Reason for revert: Looks like it closed the tree

https://ci.chromium.org/ui/p/chromium/builders/ci/chromeos-arm-generic-dbg/49672/blamelist

The error is about resources.

[1549/76611] ACTION //chromeos/components/hps:hps_internals_ts(//build/toolchain/cros:target)
FAILED: gen/chromeos/components/hps/tsconfig.json gen/chromeos/components/hps/tsconfig.manifest gen/chromeos/components/hps/resources/hps_internals.js
python3 ../../tools/typescript/ts_library.py --root_dir ../../chromeos/components/hps --gen_dir gen/chromeos/components/hps --out_dir gen/chromeos/components/hps --in_files resources/hps_internals.ts --definitions ../../../../../../tools/typescript/definitions/chrome_send.d.ts --path_mappings chrome://resources/\*\|../../../ui/webui/resources/preprocessed/\* //resources/\*\|../../../ui/webui/resources/preprocessed/\* chrome://resources/polymer/v3_0/\*\|../../../../../../third_party/polymer/v3_0/components-chromium/\* //resources/polymer/v3_0/\*\|../../../../../../third_party/polymer/v3_0/components-chromium/\* chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js\|../../../../../../third_party/polymer/v3_0/components-chromium/polymer/polymer.d.ts //resources/polymer/v3_0/polymer/polymer_bundled.min.js\|../../../../../../third_party/polymer/v3_0/components-chromium/polymer/polymer.d.ts /tools/typescript/definitions/\*\|../../../../../../tools/typescript/definitions/\*
Traceback (most recent call last):
  File "../../tools/typescript/ts_library.py", line 153, in <module>
    main(sys.argv[1:])
  File "../../tools/typescript/ts_library.py", line 117, in main
    node.RunNode([
  File "/b/s/w/ir/cache/builder/src/out/Debug/../../third_party/node/node.py", line 34, in RunNode
    raise RuntimeError('Command \'%s\' failed\n%s' % (' '.join(cmd), err))
RuntimeError: Command '/b/s/w/ir/cache/builder/src/out/Debug/../../third_party/node/linux/node-linux-x64/bin/node /b/s/w/ir/cache/builder/src/out/Debug/../../third_party/node/node_modules/typescript/bin/tsc --project gen/chromeos/components/hps/tsconfig.json' failed
../../chromeos/components/hps/resources/hps_internals.ts:6:32 - error TS2792: Cannot find module 'chrome://resources/js/cr.m.js'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

6 import {addWebUIListener} from 'chrome://resources/js/cr.m.js';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../chromeos/components/hps/resources/hps_internals.ts:7:17 - error TS2792: Cannot find module 'chrome://resources/js/util.m.js'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

7 import {$} from 'chrome://resources/js/util.m.js';

Original change's description:
> Enable unused resource removal for android webview
>
> Bug: 1269757
> Change-Id: Ib3077a1c56f32b8de5df391ee19aae1790ae507f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3534059
> Auto-Submit: Mohamed Heikal <mheikal@chromium.org>
> Reviewed-by: Richard Coles <torne@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#984640}

Bug: 1269757
Change-Id: I8811142db0fb070881aafa68e7ecc2d0ef594635
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3546167
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Fergal Daly <fergal@google.com>
Commit-Queue: Fergal Daly <fergal@chromium.org>
Cr-Commit-Position: refs/heads/main@{#984657}
NOKEYCHECK=True
GitOrigin-RevId: b4682a771075bee5f29c218de06f0367634b8f68