Revert "Add --disable-test-server to test_runner.py"
This reverts commit 349378d019dee364614412ba651d42c9300f6e04.

Reason for revert: The last 3 build of android-10-x86-chrome-tests include this change and all fail with
  AttributeError: 'AvdArgs' object has no attribute `disable_test_server'

The linked bug has a full log and more links.

Original change's description:
> Add --disable-test-server to test_runner.py
>
> ss on WSL2 will print out '127.0.0.1:5037', so isn't excepted by the
> existing forwarder detection. Adding that value or checking for
> ADB_SERVER_SOCKET breaks emulator based tests unfortunately.
>
> As such just add a new flag --disable-test-server which avoids the
> test server spawn.
>
> Bug: 1030827
> Change-Id: Ia53a9b08dc4c3e874f290b834b71d85413a8bd0a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4287950
> Commit-Queue: Benjamin Joyce (Ben) <bjoyce@chromium.org>
> Auto-Submit: Dale Curtis <dalecurtis@chromium.org>
> Reviewed-by: Benjamin Joyce (Ben) <bjoyce@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1109432}

Bug: 1030827
Change-Id: I6690b14f412206a63302837e7bc442a406c7720e
Fixed: 1418950
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4288769
Commit-Queue: Friedrich Horschig <fhorschig@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Friedrich Horschig <fhorschig@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1109530}
NOKEYCHECK=True
GitOrigin-RevId: 3f4c0a8539c013f990aa8c4efa22f961058bcdb5