Add librt to default libs on linux
It's needed by clock_gettime() on glibc < 2.17, and that function is
called in various places in the codebase. This library is part of glibc,
so just put in the default toolchain libs so we get it everywhere.

It fixes the following build error:

gn gen out_gn_ozone --args='use_ozone=true toolkit_views=false is_component_build=true'
ninja -C out_gn_ozone content_shell

../ui/gl/sync_control_vsync_provider.cc:70: error: undefined reference to
'clock_gettime'
../ui/gl/sync_control_vsync_provider.cc:71: error: undefined reference to
'clock_gettime'

Review URL: https://codereview.chromium.org/1565983002

Cr-Original-Commit-Position: refs/heads/master@{#368383}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 651aab406b2684042fcb0d87fe5f27a68bd8764b