nacl_bootstrap: Use toolchain internal sysroot for arm64 nacl
use the bundled toolchain sysroot for arm64 builds.
Otherwise the default board sysroot is used which
causes nacl_bootstrap builds failures.

Fixes error like:
sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/asm/
sigcontext.h:74:2: error: unknown type name '__uint128_t'
        __uint128_t vregs[32];
        ^

Bug: b:242104777, b:188495414
Change-Id: Ibaff2ebb931e3fbf5a3fc192e751789b10843444
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3873509
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Manoj Gupta <manojgupta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1043742}
NOKEYCHECK=True
GitOrigin-RevId: 0d2ba978bf12eda325133182120b1261cd5c2e2a