Revert 220846 "Make landmines.py take an extra script via an env..."
It broke telemetry_unittests.
http://build.chromium.org/p/chromium.win/builders/Win%207%20Tests%20x64%20%283%29/builds/8782/steps/telemetry_unittests/logs/stdio

E:\b\depot_tools\python_bin\python_slave.exe src\tools\telemetry\run_tests --browser=release_x64
No adb found in $PATH, fallback to checked in binary.
Traceback (most recent call last):
  File "src\tools\telemetry\run_tests", line 8, in <module>
    from telemetry.unittest import gtest_testrunner
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\__init__.py", line 12, in <module>
    from telemetry.core.browser_options import BrowserFinderOptions
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\core\browser_options.py", line 12, in <module>
    from telemetry.core import browser_finder
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\core\browser_finder.py", line 9, in <module>
    from telemetry.core.backends.chrome import android_browser_finder
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\core\backends\chrome\android_browser_finder.py", line 17, in <module>
    from telemetry.core.backends.chrome import android_browser_backend
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\core\backends\chrome\android_browser_backend.py", line 15, in <module>
    from telemetry.core.backends.chrome import chrome_browser_backend
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\core\backends\chrome\chrome_browser_backend.py", line 19, in <module>
    from telemetry.core.backends.chrome import extension_dict_backend
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\core\backends\chrome\extension_dict_backend.py", line 9, in <module>
    from telemetry.core.backends.chrome import inspector_backend
  File "E:\b\build\slave\Win_7_Tests_x64__3_\build\src\tools\telemetry\telemetry\core\backends\chrome\inspector_backend.py", line 19, in <module>
    from telemetry.core.jsheap import model
ImportError: No module named jsheap

> Make landmines.py take an extra script via an env var.
> 
> The extra Python script to run can be specified via env var
> EXTRA_LANDMINES_SCRIPT.
> 
> BUG=223636
> 
> Review URL: https://chromiumcodereview.appspot.com/23604016

TBR=sivachandra@chromium.org

Review URL: https://codereview.chromium.org/23533016

git-svn-id: http://src.chromium.org/svn/trunk/src/build@220853 4ff67af0-8c30-449e-8e8b-ad334ec8d88c