generate_gradle: Allow android_sdk_version to be int
Gradle generation failed for me with:
  File ".../generate_gradle.py", line 526, in _GenerateBaseVars
    if target_sdk_version.isalpha():
AttributeError: 'int' object has no attribute 'isalpha'

The value is coming from $OUT/build_vars.json, which has this relevant
line:
```
"android_sdk_version": 31,
```

Eliminating the AttributeError fixes the gradle generation, but the
Studio is still stuck unable to find the SDK with the path "android-31".

Adding this line to args.gn fixes it for me:
```
android_sdk_version = 30
```

Bug: None
Change-Id: Iaa637e0a3a7fff146acbedc00b0239096fb9dc20
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2985519
Commit-Queue: Egor Pasko <pasko@chromium.org>
Reviewed-by: Peter Wen <wnwen@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#895642}
NOKEYCHECK=True
GitOrigin-RevId: 92738037e9bd584d59155c9089eb5aa4c0927131