Fix crash during build/gyp_chromium time.
Without GYP_DEFINES set, build/gyp_chromium would crash with

Generating gyp files from GN...
Traceback (most recent call last):
  File "./build/gyp_chromium", line 207, in <module>
    if not RunGN(supplemental_includes):
  File "./build/gyp_chromium", line 147, in RunGN
    gyp_vars = GetVarsStringForGN(supplemental_includes)
  File "./build/gyp_chromium", line 79, in GetVarsStringForGN
    items = shlex.split(env_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 124, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

This was broken by r238475

BUG=321352

Review URL: https://codereview.chromium.org/103253002

git-svn-id: http://src.chromium.org/svn/trunk/src/build@238486 4ff67af0-8c30-449e-8e8b-ad334ec8d88c