Fix Linux font install for Python 3
install-chromeos-fonts.py references python, which is not guaranteed to
be installed (at least not on Googler machines). Instead, python2 and
python3 are guaranteed available (in depot_tools if not elsewhere).

This leads to this error message:

    Installing Chrome OS fonts.
    /usr/bin/env: ‘python’: No such file or directory
    ERROR: The installation of the Chrome OS default fonts failed.

The remainder of the error message is misleading (in this context) and
has a spelling error which this also fixes.

Change-Id: Ie05a95d654a51448240f3910dd4bb54a32f54336
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3539216
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#983457}
NOKEYCHECK=True
GitOrigin-RevId: b26115f8dfb584a6fd773d72a3b80c9420972f92