mac/arm: Disable -Wmax-tokens.
-Wmax-tokens coverage on mac/intel should be sufficient for now.
We just need to remember to switch this when we turn down the intel
mac bots in a decade or so.

../../content/public/browser/content_browser_client.cc:12:31: error:
   the number of preprocessor source tokens (902784) exceeds this token limit (860000) [-Werror,-Wmax-tokens]
    #pragma clang max_tokens_here 860000
                                  ^

Bug: 1098899
Change-Id: I5ddefd30b39cffb0a9aacd2838847c9c06d3fe93
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2281319
Auto-Submit: Nico Weber <thakis@chromium.org>
Commit-Queue: Hans Wennborg <hans@chromium.org>
Reviewed-by: Hans Wennborg <hans@chromium.org>
Cr-Commit-Position: refs/heads/master@{#785300}
GitOrigin-RevId: 9c60dd3942545004a79dc4733783ed03fd277e5f