Revert of -fno-exceptions only on .cc files (patchset #1 id:1 of https://codereview.chromium.org/560873003/)
Reason for revert:
Causes ASAN LSAN Linux bot to fail (not in the CQ/try set):

[191/22134 | 8.047] CC obj/third_party/speex/libspeex/libspeex.filters.o
FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/libc++abi/trunk/src/libc++abi.cxa_new_delete.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DCHROMIUM_BUILD -DCR_CLANG_REVISION=214024 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DUSE_XI2_MT=2 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DADDRESS_SANITIZER -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DUSE_NSS=1 -DLEAK_SANITIZER -DWTF_USE_LEAK_SANITIZER=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen '-I../../third_party/libc++abi/trunk/include' '-I../../third_party/libc++/trunk/include' -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /b/build/slave/Linux_ASan_LSan_Builder/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/b/build/slave/Linux_ASan_LSan_Builder/build/src/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -fstrict-aliasing -nostdinc++ -std=c++11 -Wno-format -Wno-unused-result -m64 -march=x86-64 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize=leak -O2 -fdata-sections -ffunction-sections -fno-slp-vectorize -funwind-tables -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-deprecated  -c ../../third_party/libc++abi/trunk/src/cxa_new_delete.cpp -o obj/third_party/libc++abi/trunk/src/libc++abi.cxa_new_delete.o
../../third_party/libc++abi/trunk/src/cxa_new_delete.cpp:50:13: error: cannot use 'throw' with exceptions disabled
            throw std::bad_alloc();
            ^
../../third_party/libc++abi/trunk/src/cxa_new_delete.cpp:77:5: error: cannot use 'try' with exceptions disabled
    try
    ^
../../third_party/libc++abi/trunk/src/cxa_new_delete.cpp:118:5: error: cannot use 'try' with exceptions disabled
    try
    ^
3 errors generated.
FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/libc++abi/trunk/src/libc++abi.cxa_aux_runtime.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DCHROMIUM_BUILD -DCR_CLANG_REVISION=214024 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DUSE_XI2_MT=2 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DADDRESS_SANITIZER -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DUSE_NSS=1 -DLEAK_SANITIZER -DWTF_USE_LEAK_SANITIZER=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen '-I../../third_party/libc++abi/trunk/include' '-I../../third_party/libc++/trunk/include' -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /b/build/slave/Linux_ASan_LSan_Builder/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/b/build/slave/Linux_ASan_LSan_Builder/build/src/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -fstrict-aliasing -nostdinc++ -std=c++11 -Wno-format -Wno-unused-result -m64 -march=x86-64 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize=leak -O2 -fdata-sections -ffunction-sections -fno-slp-vectorize -funwind-tables -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-deprecated  -c ../../third_party/libc++abi/trunk/src/cxa_aux_runtime.cpp -o obj/third_party/libc++abi/trunk/src/libc++abi.cxa_aux_runtime.o
../../third_party/libc++abi/trunk/src/cxa_aux_runtime.cpp:24:5: error: cannot use 'throw' with exceptions disabled
    throw std::bad_cast();
    ^
../../third_party/libc++abi/trunk/src/cxa_aux_runtime.cpp:29:5: error: cannot use 'throw' with exceptions disabled
    throw std::bad_typeid();
    ^
2 errors generated.
FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/libc++abi/trunk/src/libc++abi.cxa_personality.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DCHROMIUM_BUILD -DCR_CLANG_REVISION=214024 -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DUSE_XI2_MT=2 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DUSE_UDEV -DENABLE_EGLIMAGE=1 -DADDRESS_SANITIZER -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DCLD2_DATA_SOURCE=static -DENABLE_FULL_PRINTING=1 -DENABLE_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DUSE_NSS=1 -DLEAK_SANITIZER -DWTF_USE_LEAK_SANITIZER=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen '-I../../third_party/libc++abi/trunk/include' '-I../../third_party/libc++/trunk/include' -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -pipe -fPIC -Wno-reserved-user-defined-literal -Xclang -load -Xclang /b/build/slave/Linux_ASan_LSan_Builder/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -B/b/build/slave/Linux_ASan_LSan_Builder/build/src/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -fstrict-aliasing -nostdinc++ -std=c++11 -Wno-format -Wno-unused-result -m64 -march=x86-64 -fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize=leak -O2 -fdata-sections -ffunction-sections -fno-slp-vectorize -funwind-tables -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-deprecated  -c ../../third_party/libc++abi/trunk/src/cxa_personality.cpp -o obj/third_party/libc++abi/trunk/src/libc++abi.cxa_personality.o
../../third_party/libc++abi/trunk/src/cxa_personality.cpp:1269:21: error: cannot use 'throw' with exceptions disabled
                    throw;
                    ^
../../third_party/libc++abi/trunk/src/cxa_personality.cpp:1290:17: error: cannot use 'throw' with exceptions disabled
                throw be;
                ^
../../third_party/libc++abi/trunk/src/cxa_personality.cpp:1203:5: error: cannot use 'try' with exceptions disabled
    try
    ^
3 errors generated.
ninja: build stopped: subcommand failed.

I'm not quite sure what the actual problem is, but revert for now.

Original issue's description:
> -fno-exceptions only on .cc files
>
> R=thakis@chromium.org
> BUG=335824
>
> Committed: https://crrev.com/fad91907037b2616fe446bfbb880f8c19418de43
> Cr-Commit-Position: refs/heads/master@{#294266}

TBR=thakis@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=335824

Review URL: https://codereview.chromium.org/564493003

Cr-Original-Commit-Position: refs/heads/master@{#294270}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f004ba611b207bbb59f3b8789ac4bb6e2b7fce3b