Fix Windows-only fuchsia presubmit bugs
When running "git cl presubmit --all" on Windows there is a repeated
failure because GetHostArchFromPlatform from build\fuchsia\common.py
doesn't recognize 'AMD64' as a valid value for platform.machine().
Failures look like:

vpython3.bat c:\src\chromium\src\build\fuchsia\device_target_test.py (129.82s) failed
...======================================================================

ERROR: testNoDevicesFoundRaiseExceptionCouldNotFind (__main__.TestDiscoverDeviceTarget)
----------------------------------------------------------------------
...
  File "c:\src\chromium\src\build\fuchsia\common.py", line 48, in GetHostArchFromPlatform
    raise Exception('Unsupported host architecture: %s' % host_arch)
Exception: Unsupported host architecture: AMD64

Aside: uploading this CL from Windows hits another one of the buggy
fuchsia presubmits mentioned in this bug. I'll fix it later. It won't
block submission.

There are some failures because of the repeated pattern of creating a
temporary file with tempfile.NamedTemporaryFile and then opening it by
name, which fails on Windows. It's not clear if fixing these is
practical and probably the code is not intended to work on Windows so
it seems best to simply not run these tests on Windows.

Bug: 1309977
Change-Id: I9c99e0bcb8d7f2828a1ce1e8f96ced16571fad0e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3549939
Reviewed-by: Wez <wez@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#986025}
NOKEYCHECK=True
GitOrigin-RevId: 117c74d652a817cc28617c633fea16c8a18d265a