Revert "[WebLayer] Update Fragment.getActivity() implementation."
This reverts commit d3f64670f510cec1aaaa43cd6d5b00365dc7bfcd.

Reason for revert: Broke several chrome_junit_tests
See https://ci.chromium.org/p/chromium/builders/ci/Android%20arm%20Builder%20%28dbg%29/53156
Sample broken chrome_junit_tests: ConfirmSyncDataStateMachineDelegateTest

Original change's description:
> [WebLayer] Update Fragment.getActivity() implementation.
>
> This CL updates the bytecode modifications we perform on
> Fragment.getActivity() to have it call ContextUtils.activityFromContext(
> getContext()), and modifies compile_java.py to detect compilation errors
> related to this change and print a message pointing you to documentation
> about the bytecode modifications.
>
> A compilation error will now print:
> ../...../PasswordEntryEditor.java:144: error: cannot find symbol
>                 getActivity().getSupportFragmentManager(),
>                              ^
>   symbol:   method getSupportFragmentManager()
>   location: class Activity
>             Expecting a FragmentActivity? See docs/.......md
>
> Bug: 1123216
> Change-Id: I04016e30fba46c7d5c592e9ab2c5e5fa4c4cfde1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2508352
> Commit-Queue: Robbie McElrath <rmcelrath@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Natalie Chouinard <chouinard@chromium.org>
> Reviewed-by: Boris Sazonov <bsazonov@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#828643}

TBR=twellington@chromium.org,agrieve@chromium.org,bsazonov@chromium.org,rmcelrath@chromium.org,chouinard@chromium.org

Change-Id: Iee2c469e87e9067bdf7ea2c1744398c473328711
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1123216
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2547121
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#828748}
GitOrigin-RevId: 9d5305e993fd8e8377426f2af8aa639d81bc54ad