Disable SkiaGold tests on Windows, skip Python 2
The unit tests in build/skia_gold_common were being run in both Python 2
and Python 3 - this changes them to Python 3 only.

The SkiaGoldSessionCompareTest tests delete their temporary files in a
way that hits permission errors on Windows so that test class is
disabled on Windows to avoid cryptic failures. A very abbreviated
version of the failures is shown here:

    in test_validOmissionOnIoError
        rc, _ = session.Compare('name', 'png_file')
    ...
    in DeleteTriageLinkFile
    PermissionError: [Errno 13] Permission denied

This change was tested with this command:

    git cl presubmit --files=build/skia_gold_common/*

Bug: 1309977
Change-Id: Id57b17762ec0162a4edef3a3313c52b2395a1bfb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3587863
Reviewed-by: Reid Kleckner <rnk@chromium.org>
Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/main@{#993800}
NOKEYCHECK=True
GitOrigin-RevId: e72ce9eb225c49918c93607faecf60d56ca487d0