Revert "Don't hardcode output directory in findbugs.py"
This reverts commit 42e7514f5c983268e38ff8773cd6544af081ebab.

It is breaking the bots like this:
https://chromegw.corp.google.com/i/clank/builders/clang-builder/builds/3819
Traceback (most recent call last):
...
Exception: The BUILDTYPE environment variable has not been set

The reason is that the downstream clang-builder uses recipes, and recipes don't
set environment variables between steps. The recipe being used is
android_builder which can be checkout as part of the buildbot code in dir:
build/scripts/slave/recipes/android/.

TBR=andrewhayden@google.com
BUG=357190

Review URL: https://codereview.chromium.org/217893002

git-svn-id: http://src.chromium.org/svn/trunk/src/build@260458 4ff67af0-8c30-449e-8e8b-ad334ec8d88c