Revert "Proguard conditional keeps for layouts"
This reverts commit 58305bfdd42a37595b26cde39585309d2a7fb85f.

Reason for revert: Suspected of breaking the build on android-archive-rel:
https://ci.chromium.org/p/chromium/builders/ci/android-archive-rel

See, e.g.:
https://ci.chromium.org/p/chromium/builders/ci/android-archive-rel/3259

Sample of error text (from https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8905843707559698656/+/steps/compile/0/stdout):

FAILED: gen/chrome/android/chrome_public_test_apk__apk/classes.dex.zip apks/ChromePublicTest.apk.mapping gen/chrome/android/chrome_public_test_apk__apk/classes.dex.zip.proguard_flags 
python ../../build/android/gyp/proguard.py --depfile [...]
Traceback (most recent call last):
  File "../../build/android/gyp/proguard.py", line 313, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../build/android/gyp/proguard.py", line 241, in main
    run_r8(cmd)
  File "../../build/android/gyp/proguard.py", line 228, in run_r8
    stderr_filter=stderr_filter)
  File "/b/s/w/ir/cache/builder/src/build/android/gyp/util/build_utils.py", line 231, in CheckOutput
    raise CalledProcessError(cwd, args, stdout + stderr)
> util.build_utils.CalledProcessError: Command failed: ( cd /b/s/w/ir/cache/builder/src/out/Release; java -jar [...]


Original change's description:
> Proguard conditional keeps for layouts
> 
> Added flag for aapt2 link to generate proguard conditional keep rules.
> 
> Bug: 682786
> Change-Id: I11e7afd5b540bcc6bc0f4bf54a8bd20c750fb0a3
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1723796
> Commit-Queue: Harsh Patel <harshpa@google.com>
> Reviewed-by: Sam Maier <smaier@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#684463}

TBR=agrieve@chromium.org,smaier@chromium.org,harshpa@google.com

Change-Id: Id1effbfba1810ff805b424c99a3982d8fc9c870c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 682786
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1738472
Reviewed-by: Justin Donnelly <jdonnelly@chromium.org>
Commit-Queue: Justin Donnelly <jdonnelly@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#684527}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8480ccabdb4f79556d751f4e9b371468fe1a049a